apiVersion: v1
kind: Secret
metadata:
  name: yandex-csi-os-secret
  namespace: kube-system
stringData:
  accessKeyID: YCAJEjCIbNlrN_uw4sG-H8Kdp
  secretAccessKey: YCOTW1o-QooD8ZrWPRn4dZTd1Wm68lFkalGUzElS
  endpoint: https://storage.yandexcloud.net