apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-sc-yandex-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-sc-yandex