kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-sc-yandex
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  options: "--memory-limit=1000 --dir-mode=0777 --file-mode=0666"
  bucket: csi-bucket-dsurov
  csi.storage.k8s.io/provisioner-secret-name: yandex-csi-os-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: yandex-csi-os-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: yandex-csi-os-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: yandex-csi-os-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system