apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-role-min
rules:
- apiGroups: ["otus.homework"]
  resources: ["mysqls"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["create", "patch", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "patch", "update", "delete"]