apiVersion: v1
kind: Pod
metadata:
  name: nginx-debug
  namespace: default
spec:
  shareProcessNamespace: true
  containers:
   - name: nginx-debug
     image: kyos0109/nginx-distroless
     ports:
     - containerPort: 80
     volumeMounts:
       - mountPath: /data
         name: mydir
         
  volumes:
  - name: mydir
    emptyDir: {}