apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: homework
  labels:
    team: nginx
spec:
  selector:
    matchLabels:
      app: nginx-service
  endpoints:
    - port: exporter
