apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: homework
  labels:
    app: nginx-service
spec:
  selector:
    app: nginx-lbl-pod
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
    - name: exporter
      port: 9113
      protocol: TCP
      targetPort: 9113
