apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.specontainer.volumes.configMap.name }}
  namespace: {{ .Values.deployment.namespace }}
data:
  email: denisurov@gmail.com
  name: Denis
  surname: Surov
