apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Values.clusterRole.clusterRoleMon.name}}
rules:
- apiGroups:
  - ""
  resources: 
  - {{.Values.clusterRole.clusterRoleMon.resources}}
  verbs: 
  - {{.Values.clusterRole.clusterRoleMon.verbs}}
