apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.clusterRoleBinding.clusterRoleBindingMon.name}}
subjects:
- kind: {{.Values.clusterRoleBinding.clusterRoleBindingMon.subjects.kind}}
  name: {{.Values.clusterRoleBinding.clusterRoleBindingMon.subjects.name}}
  namespace: {{.Values.deployment.namespace}}
roleRef:
  kind: {{.Values.clusterRoleBinding.clusterRoleBindingMon.roleRef.kind}}
  name: {{.Values.clusterRoleBinding.clusterRoleBindingMon.roleRef.name}}
  apiGroup: rbac.authorization.k8s.io
