apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.clusterRoleBinding.clusterRoleBindingCd.name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{.Values.clusterRoleBinding.clusterRoleBindingCd.roleRef.kind}}
  name: {{.Values.clusterRoleBinding.clusterRoleBindingCd.roleRef.name}}
subjects:
- kind: {{.Values.clusterRoleBinding.clusterRoleBindingCd.subjects.kind}}
  name: {{.Values.clusterRoleBinding.clusterRoleBindingCd.subjects.name}}
  namespace: {{.Values.deployment.namespace}}
