apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.specPvc.name}}
  namespace: {{.Values.deployment.namespace}}
spec:
  accessModes: 
    - {{.Values.specPvc.accessModes}}
  resources:
    requests:
      storage: {{.Values.specPvc.storage}}
