all:
  hosts:
    node1:
      ansible_host: 192.168.5.187
      ip: 192.168.5.187
      access_ip: 192.168.5.187
    node2:
      ansible_host: 192.168.5.148
      ip: 192.168.5.148
      access_ip: 192.168.5.148
    node3:
      ansible_host: 192.168.5.235
      ip: 192.168.5.235
      access_ip: 192.168.5.235
    node4:
      ansible_host: 192.168.5.241
      ip: 192.168.5.241
      access_ip: 192.168.5.241
    node5:
      ansible_host: 192.168.5.231
      ip: 192.168.5.231
      access_ip: 192.168.5.231
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
